// ===== 服装目录（45 件，ISO 9920 clo 量级） =====
// 贴身上装 10 / 贴身下装 9 / 保温层 13 / 防护层 13
// 第四步软排序标签（styles / formality / presentation / silhouettes / colors）：
// 只参与排序与解释，不参与硬过滤与安全判定；缺省时按中性回退。

import type { ClothingItem } from './types'

const c = (item: Omit<ClothingItem, 'id'> & { id: string }): ClothingItem => item

export const CATALOG: ClothingItem[] = [
  // ---------- 贴身层 BASE ----------
  // comfortRangeC 下界 = 叠穿体系下的可穿下限（可被外层罩住），不是单穿舒适下界
  // 上装 TOP
  c({ id: 't_tank', name: '速干背心', category: 'TOP', role: 'BASE', insulationClo: 0.06, wind: 0, water: 0, breathability: 0.9, solar: 0.15, weightGrams: 120, removable: true, comfortRangeC: [14, 38], styles: ['SPORT', 'OUTDOOR'], formality: 0.15, presentation: ['UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 't_short', name: '短袖T恤', category: 'TOP', role: 'BASE', insulationClo: 0.1, wind: 0, water: 0, breathability: 0.9, solar: 0.25, weightGrams: 180, removable: true, comfortRangeC: [12, 34], styles: ['DAILY', 'SPORT'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 't_tee', name: '纯棉T恤', category: 'TOP', role: 'BASE', insulationClo: 0.12, wind: 0, water: 0, breathability: 0.8, solar: 0.2, weightGrams: 200, removable: true, comfortRangeC: [10, 32], styles: ['DAILY', 'JAPANESE_LOOSE'], formality: 0.25, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['NEUTRAL'] }),
  c({ id: 't_polo', name: 'Polo衫', category: 'TOP', role: 'BASE', insulationClo: 0.16, wind: 0, water: 0, breathability: 0.75, solar: 0.25, weightGrams: 240, removable: true, comfortRangeC: [8, 30], styles: ['DAILY', 'COMMUTE'], formality: 0.45, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 't_longsleeve', name: '长袖棉衫', category: 'TOP', role: 'BASE', insulationClo: 0.22, wind: 0, water: 0, breathability: 0.75, solar: 0.3, weightGrams: 260, removable: true, comfortRangeC: [2, 26], styles: ['DAILY', 'KOREAN_CLEAN'], formality: 0.3, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 't_wool_base', name: '美利奴羊毛衫', category: 'TOP', role: 'BASE', insulationClo: 0.3, wind: 0, water: 0, breathability: 0.85, solar: 0.3, weightGrams: 300, removable: false, comfortRangeC: [-12, 20], styles: ['COMMUTE', 'BUSINESS'], formality: 0.4, presentation: ['UNISEX'], silhouettes: ['FITTED', 'REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 't_silk_base', name: '真丝打底衫', category: 'TOP', role: 'BASE', insulationClo: 0.26, wind: 0, water: 0, breathability: 0.8, solar: 0.3, weightGrams: 220, removable: false, comfortRangeC: [-8, 24], styles: ['BUSINESS', 'COMMUTE'], formality: 0.55, presentation: ['FEMININE', 'UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 't_sport_tee', name: '运动速干T恤', category: 'TOP', role: 'BASE', insulationClo: 0.1, wind: 0, water: 0.1, breathability: 0.95, solar: 0.3, weightGrams: 160, removable: true, comfortRangeC: [12, 36], styles: ['SPORT', 'OUTDOOR'], formality: 0.15, presentation: ['UNISEX'], silhouettes: ['FITTED', 'REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 't_thermal_top', name: '发热保暖内衣', category: 'TOP', role: 'BASE', insulationClo: 0.36, wind: 0, water: 0, breathability: 0.6, solar: 0.25, weightGrams: 380, removable: false, comfortRangeC: [-28, 18], styles: ['DAILY'], formality: 0.1, presentation: ['UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 't_cotton_under', name: '棉质贴身背心', category: 'TOP', role: 'BASE', insulationClo: 0.08, wind: 0, water: 0, breathability: 0.85, solar: 0.1, weightGrams: 140, removable: true, comfortRangeC: [14, 36], styles: ['DAILY'], formality: 0.12, presentation: ['UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  // 下装 BOTTOM
  c({ id: 'b_shorts', name: '运动短裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.08, wind: 0, water: 0, breathability: 0.85, solar: 0.3, weightGrams: 200, removable: true, comfortRangeC: [20, 38], styles: ['SPORT', 'DAILY'], formality: 0.15, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'b_chinos', name: '薄休闲裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.2, wind: 0, water: 0, breathability: 0.7, solar: 0.25, weightGrams: 320, removable: false, comfortRangeC: [8, 30], styles: ['COMMUTE', 'DAILY', 'KOREAN_CLEAN'], formality: 0.5, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'FITTED'], colors: ['WARM'] }),
  c({ id: 'b_jeans', name: '牛仔裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.24, wind: 0.3, water: 0, breathability: 0.4, solar: 0.2, weightGrams: 600, removable: false, comfortRangeC: [2, 24], styles: ['DAILY', 'STREET'], formality: 0.35, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['COOL'] }),
  c({ id: 'b_leggings', name: '紧身裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.18, wind: 0.2, water: 0, breathability: 0.6, solar: 0.2, weightGrams: 250, removable: false, comfortRangeC: [6, 26], styles: ['SPORT', 'DAILY'], formality: 0.2, presentation: ['FEMININE', 'UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  // 舒适窗与上装同族对齐（发热保暖内衣 −28~18）：它是穿在外裤里的保暖打底，不是单穿长裤，
  // −8 的下界会让 ≤−10℃ 的贴身高下装槽拿不到任何合格件（第五步目录审计）
  c({ id: 'b_thermal_leg', name: '发热保暖裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.32, wind: 0, water: 0, breathability: 0.5, solar: 0.2, weightGrams: 350, removable: false, comfortRangeC: [-28, 16], styles: ['DAILY'], formality: 0.1, presentation: ['UNISEX'], silhouettes: ['FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 'b_wool_pants', name: '羊毛裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.3, wind: 0.2, water: 0, breathability: 0.5, solar: 0.2, weightGrams: 400, removable: false, comfortRangeC: [-5, 18], styles: ['BUSINESS', 'COMMUTE'], formality: 0.75, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'FITTED'], colors: ['NEUTRAL'] }),
  c({ id: 'b_cargo', name: '工装裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.2, wind: 0.2, water: 0, breathability: 0.5, solar: 0.25, weightGrams: 420, removable: false, comfortRangeC: [5, 26], styles: ['STREET', 'OUTDOOR'], formality: 0.35, presentation: ['UNISEX'], silhouettes: ['LOOSE', 'REGULAR'], colors: ['WARM'] }),
  c({ id: 'b_trousers_loose', name: '阔腿裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.16, wind: 0.1, water: 0, breathability: 0.75, solar: 0.2, weightGrams: 280, removable: false, comfortRangeC: [10, 30], styles: ['JAPANESE_LOOSE', 'KOREAN_CLEAN', 'DAILY'], formality: 0.45, presentation: ['FEMININE', 'UNISEX'], silhouettes: ['LOOSE'], colors: ['WARM'] }),
  // 快干 ≠ 挡雨：water 是"抗降水"属性，排水速干属于透湿侧，不该拿防水分
  c({ id: 'b_swim_short', name: '沙滩裤', category: 'BOTTOM', role: 'BASE', insulationClo: 0.06, wind: 0, water: 0.1, breathability: 0.9, solar: 0.3, weightGrams: 150, removable: true, comfortRangeC: [24, 40], styles: ['SPORT', 'DAILY'], formality: 0.1, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['BRIGHT'] }),

  // ---------- 保温层 INSULATION ----------
  // clo 已按 ASHRAE Fundamentals / ISO 9920 Annex B 核对：
  // 卫衣 ~0.35-0.40、厚毛衣 ~0.45-0.50、抓绒 ~0.40-0.45、轻薄羽绒 ~0.90-1.0
  // comfortRangeC 下界 = 叠穿体系下的可穿下限（外层罩住），不是单穿舒适下界
  c({ id: 'i_hoodie', name: '连帽卫衣', category: 'TOP', role: 'INSULATION', insulationClo: 0.4, wind: 0.4, water: 0, breathability: 0.5, solar: 0.3, weightGrams: 500, removable: true, comfortRangeC: [-6, 20], styles: ['STREET', 'DAILY', 'SPORT'], formality: 0.25, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['NEUTRAL'] }),
  c({ id: 'i_cardigan', name: '针织开衫', category: 'TOP', role: 'INSULATION', insulationClo: 0.4, wind: 0.3, water: 0, breathability: 0.6, solar: 0.3, weightGrams: 420, removable: true, comfortRangeC: [-4, 22], styles: ['DAILY', 'KOREAN_CLEAN'], formality: 0.45, presentation: ['FEMININE', 'UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'i_sweater', name: '羊毛毛衣', category: 'TOP', role: 'INSULATION', insulationClo: 0.5, wind: 0.4, water: 0, breathability: 0.5, solar: 0.3, weightGrams: 550, removable: true, comfortRangeC: [-14, 16], styles: ['COMMUTE', 'DAILY', 'JAPANESE_LOOSE'], formality: 0.5, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'i_fleece', name: '抓绒衣', category: 'TOP', role: 'INSULATION', insulationClo: 0.45, wind: 0.3, water: 0, breathability: 0.6, solar: 0.3, weightGrams: 480, removable: true, comfortRangeC: [-12, 18], styles: ['OUTDOOR', 'SPORT', 'DAILY'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'i_down_layer', name: '轻薄羽绒服', category: 'TOP', role: 'INSULATION', insulationClo: 0.95, wind: 0.6, water: 0, breathability: 0.3, solar: 0.4, weightGrams: 700, removable: true, comfortRangeC: [-20, 8], styles: ['DAILY', 'OUTDOOR'], formality: 0.35, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'i_vest', name: '保暖马甲', category: 'TOP', role: 'INSULATION', insulationClo: 0.5, wind: 0.4, water: 0, breathability: 0.6, solar: 0.4, weightGrams: 380, removable: true, comfortRangeC: [-14, 14], styles: ['OUTDOOR', 'DAILY', 'STREET'], formality: 0.3, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'i_denim_jacket', name: '牛仔外套', category: 'TOP', role: 'INSULATION', insulationClo: 0.45, wind: 0.5, water: 0.3, breathability: 0.4, solar: 0.3, weightGrams: 700, removable: true, comfortRangeC: [-4, 18], styles: ['STREET', 'DAILY'], formality: 0.4, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['COOL'] }),
  c({ id: 'i_blazer', name: '西装外套', category: 'TOP', role: 'INSULATION', insulationClo: 0.42, wind: 0.4, water: 0, breathability: 0.5, solar: 0.3, weightGrams: 550, removable: true, comfortRangeC: [2, 20], styles: ['BUSINESS', 'COMMUTE'], formality: 0.8, presentation: ['UNISEX'], silhouettes: ['FITTED', 'REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'i_bomber', name: '棒球夹克', category: 'TOP', role: 'INSULATION', insulationClo: 0.55, wind: 0.6, water: 0.3, breathability: 0.4, solar: 0.3, weightGrams: 650, removable: true, comfortRangeC: [-8, 16], styles: ['STREET', 'SPORT'], formality: 0.3, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'i_padded_jacket', name: '棉服', category: 'TOP', role: 'INSULATION', insulationClo: 1.0, wind: 0.5, water: 0.3, breathability: 0.3, solar: 0.35, weightGrams: 900, removable: false, comfortRangeC: [-22, 6], styles: ['DAILY', 'OUTDOOR'], formality: 0.3, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'i_quilted_vest', name: '充绒马甲', category: 'TOP', role: 'INSULATION', insulationClo: 0.65, wind: 0.5, water: 0, breathability: 0.5, solar: 0.35, weightGrams: 420, removable: true, comfortRangeC: [-18, 10], styles: ['DAILY', 'BUSINESS', 'COMMUTE'], formality: 0.55, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'i_mid_cotton', name: '摇粒绒打底', category: 'TOP', role: 'INSULATION', insulationClo: 0.48, wind: 0.3, water: 0, breathability: 0.65, solar: 0.3, weightGrams: 400, removable: true, comfortRangeC: [-10, 18], styles: ['OUTDOOR', 'DAILY'], formality: 0.25, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  // 没有"保暖下装槽"：厚裙按贴身下装的替代品参与 BASE 池（原 INSULATION/BOTTOM 无槽位能命中，结构不可达）
  c({ id: 'i_skirt_thick', name: '厚裙', category: 'BOTTOM', role: 'BASE', insulationClo: 0.28, wind: 0.2, water: 0, breathability: 0.6, solar: 0.25, weightGrams: 350, removable: true, comfortRangeC: [6, 24], styles: ['DAILY', 'KOREAN_CLEAN'], formality: 0.45, presentation: ['FEMININE'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),

  // ---------- 防护层 PROTECTION ----------
  c({ id: 'p_windbreaker', name: '防风夹克', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.25, wind: 0.9, water: 0.4, breathability: 0.5, solar: 0.4, weightGrams: 450, removable: true, comfortRangeC: [4, 22], shellGrade: 1, styles: ['OUTDOOR', 'DAILY', 'SPORT'], formality: 0.25, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'p_raincoat', name: '雨衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.1, wind: 0.8, water: 0.98, breathability: 0.1, solar: 0.3, weightGrams: 400, removable: true, comfortRangeC: [2, 26], shellGrade: 3, styles: ['OUTDOOR', 'DAILY'], formality: 0.15, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'p_hardshell', name: '硬壳冲锋衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.35, wind: 1.0, water: 1.0, breathability: 0.35, solar: 0.5, weightGrams: 650, removable: true, comfortRangeC: [-5, 22], shellGrade: 3, styles: ['OUTDOOR'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'p_softshell', name: '软壳衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.4, wind: 0.85, water: 0.7, breathability: 0.55, solar: 0.45, weightGrams: 550, removable: true, comfortRangeC: [-2, 20], shellGrade: 2, styles: ['OUTDOOR', 'DAILY'], formality: 0.3, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['NEUTRAL'] }),
  c({ id: 'p_down_coat', name: '羽绒服', category: 'OUTER', role: 'PROTECTION', insulationClo: 1.2, wind: 0.8, water: 0.5, breathability: 0.2, solar: 0.3, weightGrams: 1200, removable: false, comfortRangeC: [-25, 2], shellGrade: 1, styles: ['DAILY', 'COMMUTE'], formality: 0.4, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['NEUTRAL'] }),
  c({ id: 'p_parajumpers', name: '派克服', category: 'OUTER', role: 'PROTECTION', insulationClo: 1.15, wind: 0.75, water: 0.6, breathability: 0.25, solar: 0.3, weightGrams: 1300, removable: false, comfortRangeC: [-20, 0], shellGrade: 1, styles: ['STREET', 'COMMUTE'], formality: 0.45, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'p_sun_jacket', name: '防晒衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.12, wind: 0.3, water: 0.2, breathability: 0.8, solar: 0.9, weightGrams: 180, removable: true, comfortRangeC: [16, 36], shellGrade: 0, styles: ['OUTDOOR', 'SPORT', 'DAILY'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'FITTED'], colors: ['BRIGHT'] }),
  c({ id: 'p_trench', name: '风衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.3, wind: 0.7, water: 0.6, breathability: 0.4, solar: 0.35, weightGrams: 600, removable: true, comfortRangeC: [2, 18], shellGrade: 1, styles: ['COMMUTE', 'BUSINESS'], formality: 0.7, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'p_swim_jacket', name: '防水冲锋衣', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.4, wind: 1.0, water: 1.0, breathability: 0.3, solar: 0.5, weightGrams: 700, removable: true, comfortRangeC: [-5, 20], shellGrade: 3, styles: ['OUTDOOR', 'SPORT'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'p_vintage', name: '复古厚夹克', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.5, wind: 0.7, water: 0.5, breathability: 0.35, solar: 0.3, weightGrams: 800, removable: true, comfortRangeC: [-2, 16], shellGrade: 1, styles: ['STREET', 'DAILY'], formality: 0.35, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['WARM'] }),
  c({ id: 'p_umbrella_vest', name: '防晒帽衫', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.18, wind: 0.25, water: 0.3, breathability: 0.7, solar: 0.85, weightGrams: 250, removable: true, comfortRangeC: [12, 34], shellGrade: 0, styles: ['DAILY', 'SPORT'], formality: 0.2, presentation: ['UNISEX'], silhouettes: ['LOOSE', 'REGULAR'], colors: ['BRIGHT'] }),
  c({ id: 'p_pvc_poncho', name: '轻便雨披', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.05, wind: 0.5, water: 0.99, breathability: 0.05, solar: 0.25, weightGrams: 220, removable: true, comfortRangeC: [5, 30], shellGrade: 3, styles: ['OUTDOOR', 'DAILY'], formality: 0.15, presentation: ['UNISEX'], silhouettes: ['LOOSE'], colors: ['BRIGHT'] }),
  c({ id: 'p_linen_jacket', name: '亚麻西装外套', category: 'OUTER', role: 'PROTECTION', insulationClo: 0.2, wind: 0.3, water: 0.1, breathability: 0.8, solar: 0.6, weightGrams: 350, removable: true, comfortRangeC: [14, 30], shellGrade: 0, styles: ['COMMUTE', 'BUSINESS', 'DAILY'], formality: 0.6, presentation: ['UNISEX'], silhouettes: ['REGULAR', 'LOOSE'], colors: ['NEUTRAL'] }),
]

/** 按角色分组索引 */
export const catalogByRole = (role: 'BASE' | 'INSULATION' | 'PROTECTION') =>
  CATALOG.filter((i) => i.role === role)

export const catalogByCategory = (category: 'TOP' | 'BOTTOM' | 'OUTER') =>
  CATALOG.filter((i) => i.category === category)
